### ISSUE TITLE
Intro Section

### ISSUE THREAD

**Issue by sjkoelle** [sjkoelle/Prelim#1]
Ready for you to read VM!

**Comment by vnminin** [comment]
Writeup.tex doesn't compile for me -- giving me some math mode errors.

**Comment by sjkoelle** [comment]
Me too.  However, I can press enter about 5 times and it compiles into
something reasonable.  Does this work for you?  I can also send a PDF.

Sam

**Comment by vnminin** [comment]
Have you made me a collaborator? For some reason I cannot push, so maybe not?

**Comment by sjkoelle** [comment]
Try now

On Thu, May 19, 2016 at 9:54 AM, Vladimir N. Minin <notifications@github.com

**Comment by vnminin** [comment]
Pushed successfully.
